pipeline {
	agent any

	stages {
		stage('Clone GitHub Project') {
			steps {
				git 'https://github.com/tektutor/jenkins-bengaluru-dec-2018.git'
			}
		}
		stage('Build Docker Image') {
			steps {
				sh 'docker build -t tektutor/jenkins-slave Day2'
			}
		}
		stage('Compile Maven Project') {
			agent { docker 'tektutor/jenkins-slave' }
			steps {
				sh 'cd CRM'
				sh 'mvn clean package'
			}
		}
	}

}
